version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.11.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - js-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: js-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint Code
          command: yarn lint

  test:
    docker:
      - image: circleci/node:8.11.1
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_DB: oncohelp
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install MySQL client
          command: sudo apt-get install -y mysql-client
      - restore_cache:
          keys:
            - js-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: js-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Test Code (unit)
          command: yarn test
      - run:
          name: Test Code (e2e)
          command: yarn test:e2e

workflows:
  version: 2
  check-pr:
    jobs:
      - lint:
          filters:
            branches:
              ignore: 
                - master
      - test:
          filters:
            branches:
              ignore:
                - master
