version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.11.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - js-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: js-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint Code
          command: yarn lint

  test:
    docker:
      - image: circleci/node:8.11.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - js-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: js-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Test Code (unit)
          command: yarn test
      - run:
          name: Test Code (e2e)
          command: yarn test:e2e

workflows:
  version: 2
  check-pr:
    jobs:
      - lint:
          filters:
            branches:
              ignore: 
                - master
      - test:
          filters:
            branches:
              ignore:
                - master
