ALTER TABLE claim
    ADD COLUMN _editedAt TIMESTAMP DEFAULT NOW();
    ADD COLUMN _answeredAt TIMESTAMP DEFAULT NOW();
    ADD COLUMN _answerUpdatedAt TIMESTAMP DEFAULT NOW();

#DOWN

ALTER TABLE claim
    DROP COLUMN _editedAt
    DROP COLUMN _answeredAt
    DROP COLUMN _answerUpdatedAt